### ISSUE TITLE
Number.EPSILON support

### ISSUE THREAD

**Issue by cygnyx** [albertosantini/node-quadprog#3]
Node.js currently doesn't support Number.EPSILON. Mozilla reports that it isn't available in several browsers and its value is about 2.2204460492503130808472633361816E-16. 
I ran the previous version that included the vsmall calculation and found its value to be 1.4272476927059598e-15. Since javascript is numerically stable across platforms it is likely that this value will work in multiple environments.  I obtained the same value using Safari browser on JSFiddle. I tested Number.EPSILON and 1.43e-15 as initial values to the vsmall calculation with surprising results. Assuming the vsmall calculation is related to the calculations used in the algorithm, then Number.EPSILON may be too small. When I used the Number.EPSILON constant in my test problems I obtained the same results.

Can you change line 99 from:
    vsmall = Number.EPSILON;
to:
    vsmall = Number.EPSILON || 2.2204460492503130808472633361816E-16;

Since vsmall is only used to test values near zero, it seems like Number.EPSILON is usable. In reviewing the code, I noticed that one comparison uses '<=' while the others use '<'.

**Comment by albertosantini** [comment]
I think I revert the change, using the original code calculating  `vsmall`.

The comparisons are different also in the original FORTRAN code.
You may give a look at the code `solve.QP.f` on CRAN.

Tonight I create a new release: 1.3.0.

Thanks for the feedback! :)

**Comment by albertosantini** [comment]
Published 1.3.0.

**Comment by cygnyx** [comment]
Thank you! Your solution will operate slightly faster since vsmall is calculated only once. If you are concerned about performance, have you consider declaring the work array to be:

new Float64Array(2 * n + (r * (r + 5)) / 2 + 2 * q + 1)

Since the work array is only used internally this might improve performance without changing the interface. I think that all browsers and javascript environments support typed arrays now.

**Comment by albertosantini** [comment]
Thanks, Typed Arrays are in my radar. Maybe in 2.0.
